//! MODULE-017 skills-tools-mcp canonical dependency-inversion surface.
//!
//! Canonical source: `docs/modules/MODULE-017-skills-tools-mcp.md` §2.3
//! (SkillStateReader + SkillInfo + Provenance). `TrustLevel` is canonically
//! declared in [`crate::security_validator`] (MODULE-012 owner) and
//! re-exported from this module for MODULE-017 consumer ergonomics.
//!
//! Verbatim hoist — if the owner module's declaration changes, run
//! `/spec MODULE-017` and re-hoist via a follow-on /dev slice.
//!
//! # Security posture
//!
//! - **Identifier validation**: `SkillStateReader::{skill_version,
//!   provenance, trust_level}` take `&str` `skill_id` unchecked. Implementers
//!   MUST whitelist-validate against `^[A-Za-z0-9_-]{1,128}$` before HashMap
//!   lookup to prevent cross-skill collision, control-char injection, and
//!   unbounded-key-insertion DoS from attacker-crafted skill manifests.
//! - **`SkillInfo` attacker-influenced fields**: `name` and `version` may
//!   originate from skill YAML frontmatter parsed from untrusted pack
//!   sources. Consumers rendering `name` into LLM context MUST route through
//!   [`crate::security_validator::PromptInjectionHelpers::wrap_with_boundary`]
//!   with the skill's `TrustLevel`.

use serde::{Deserialize, Serialize};

// Re-export TrustLevel here so MODULE-017's consumer-side call sites can
// import from `advance_shared_types::skills::TrustLevel` or directly from
// `advance_shared_types::security_validator::TrustLevel`. Canonical
// declaration home stays in security_validator.rs per MODULE-012 §2.3:604.
pub use crate::security_validator::TrustLevel;

/// MODULE-017 §2.3 — skill provenance discriminator.
#[derive(Clone, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum Provenance {
    /// Skill was generated by an agent via `cap-skills` propose-draft flow.
    AgentCreated,
    /// Skill was imported from a pack or admin-side source.
    Imported,
}

/// MODULE-017 §2.3:377-389 — skill inventory entry. Returned from
/// [`SkillStateReader::active_skills`] as a flat `Vec<SkillInfo>` listing
/// every currently-active skill the agent owns.
///
/// **Implementer Invariants**: bounded `skill_id` / `name` (recommended ≤ 256
/// bytes each); `version` monotonically increases on `activate-skill`;
/// `trust_level` and `provenance` MUST be consistent with MODULE-017's
/// internal skill registry.
#[derive(Clone, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SkillInfo {
    /// Stable skill identifier, matches `.agent/skills/{skill_id}/` directory name.
    pub skill_id: String,
    /// Monotonically increasing version (§1.3.1 `activate-skill` bumps this).
    pub version: u32,
    /// Human-facing name from the skill's YAML frontmatter `name` field.
    pub name: String,
    /// Origin of this skill — feeds REQ-273 provenance gating (AC-03).
    pub provenance: Provenance,
    /// Trust classification (canonical in MODULE-012 §2.3).
    pub trust_level: TrustLevel,
}

/// CONTRACT-164 — skill state read-only surface. MODULE-017 §2.3:326-331.
/// Consumed by MODULE-011 (L6 skill health) and MODULE-015 (auto-mode
/// SkillPreState tracking).
///
/// # Implementer Invariants
///
/// 1. **Read-only**: no methods mutate skill state; all mutation goes
///    through `cap-skills` host functions.
/// 2. **Consistent within a turn**: successive calls within a single
///    logical turn MUST reflect the same skill state (per-turn snapshot).
/// 3. **No skill-content materialization**: methods return metadata only;
///    skill bodies (SKILL.md content, tool.wasm bytes) load on-demand via
///    MODULE-002 fs.read, not through this trait.
/// 4. **Identifier validation**: `agent_id` / `skill_id` are untyped `&str`;
///    implementers MUST whitelist-validate before HashMap lookup.
/// 5. **Bounded output**: `active_skills` returns `Vec<SkillInfo>` capped
///    at MODULE-017's per-agent skill limit (recommended ≤ 256).
pub trait SkillStateReader: Send + Sync {
    fn active_skills(&self, agent_id: &str) -> Vec<SkillInfo>;
    fn skill_version(&self, agent_id: &str, skill_id: &str) -> Option<u32>;
    fn provenance(&self, skill_id: &str) -> Option<Provenance>;
    fn trust_level(&self, skill_id: &str) -> TrustLevel;
}
