//! The composition API: the types an embedder names to compose the runtime, receive
//! its output and stop it.

mod compose_log;
mod error;
mod extension;
mod extension_cx;
mod options;
mod runtime;

pub use crate::compose::compose;
pub use advance_shared_types::capability::CapParams;
pub use advance_shared_types::capability::GrantDecision;
pub use advance_shared_types::run::TaskRunStatus;
pub use compose_log::log_keys;
pub use compose_log::ComposeLog;
pub use compose_log::ComposeLogLine;
pub use compose_log::LogStream;
pub use compose_log::NullComposeLog;
pub use error::CapabilityRefusal;
pub use error::ComposeError;
pub use error::ExtensionFailure;
pub use error::ExtensionPhase;
pub use error::LockFailure;
pub use error::Unsupported;
pub use extension::BoxFuture;
pub use extension::ComposeExtension;
pub use extension::ExtensionError;
pub use extension::ExtensionHealth;
pub use extension::ExtensionState;
pub use extension_cx::ComposeCx;
pub use extension_cx::ConfigView;
pub use extension_cx::EmitError;
pub use extension_cx::EmitReceipt;
pub use extension_cx::ExtensionEmitter;
pub use extension_cx::ExtensionGrantCheck;
pub use extension_cx::ExtensionSecrets;
pub use extension_cx::GatewayHandle;
pub use extension_cx::RunInfo;
pub use extension_cx::RunView;
pub use extension_cx::SecretViewError;
pub use extension_cx::StartedCx;
pub use extension_cx::TaskSpawner;
pub use extension_cx::ViewError;
pub use options::Admission;
pub use options::ClientApiOptions;
pub use options::ComposeOptions;
pub use options::ComposeProfile;
pub use options::HostPlatform;
pub use options::InstanceGuard;
pub use options::ListenerOptions;
pub use options::MasterKeyInput;
pub use options::ProcessPolicy;
pub use options::WasmEngine;
pub use options::Zeroizing;
pub use runtime::ClientApiEndpoint;
pub use runtime::ComposedRuntime;
pub use runtime::InstanceGuardKind;
pub use runtime::RuntimeHealthView;
pub use runtime::RuntimePhase;
pub use runtime::ShutdownHandle;
