//! The composition API: the types an embedder names to compose the runtime, receive
//! its output and stop it.

mod compose_log;
mod error;
mod extension;
mod extension_cx;
mod host_functions;
mod inference;
mod options;
mod runtime;
mod tools;

pub use crate::compose::compose;
pub use advance_client_api::families::method_label;
pub use advance_client_api::families::ClientFamilyRegistrar;
pub use advance_client_api::families::DuplicateOf;
pub use advance_client_api::families::ExtensionCursorCodec;
pub use advance_client_api::families::ExtensionServices;
pub use advance_client_api::families::FamilyBudget;
pub use advance_client_api::families::PathDefect;
pub use advance_client_api::families::ResponseScan;
pub use advance_client_api::families::RouteOptions;
pub use advance_client_api::families::RouteRefusal;
pub use advance_client_api::families::RouteRefusalReason;
pub use advance_client_api::provider::ProviderSlot;
pub use advance_client_api::provider_or_unavailable;
pub use advance_client_api::scan_client_text;
pub use advance_client_api::ClientError;
pub use advance_client_api::ClientErrorCode;
pub use advance_client_api::ClientWarning;
pub use advance_client_api::HandlerCtx;
pub use advance_client_api::HandlerResponse;
pub use advance_client_api::HandlerSpec;
pub use advance_client_api::Method;
pub use advance_client_api::Scope;
pub use advance_shared_types::capability::CapParams;
pub use advance_shared_types::capability::GrantDecision;
pub use advance_shared_types::run::TaskRunStatus;
pub use compose_log::log_keys;
pub use compose_log::ComposeLog;
pub use compose_log::ComposeLogLine;
pub use compose_log::LogStream;
pub use compose_log::NullComposeLog;
pub use error::CapabilityRefusal;
pub use error::ComposeError;
pub use error::ExtensionFailure;
pub use error::ExtensionPhase;
pub use error::InferenceRefusal;
pub use error::InferenceSubject;
pub use error::LockFailure;
pub use error::OssBinding;
pub use error::Unsupported;
pub use extension::BoxFuture;
pub use extension::ComposeExtension;
pub use extension::ExtensionError;
pub use extension::ExtensionHealth;
pub use extension::ExtensionState;
pub use extension_cx::ComposeCx;
pub use extension_cx::ConfigView;
pub use extension_cx::EmitError;
pub use extension_cx::EmitReceipt;
pub use extension_cx::ExtensionEmitter;
pub use extension_cx::ExtensionGrantCheck;
pub use extension_cx::ExtensionSecrets;
pub use extension_cx::GatewayHandle;
pub use extension_cx::RunInfo;
pub use extension_cx::RunView;
pub use extension_cx::SecretViewError;
pub use extension_cx::StartedCx;
pub use extension_cx::TaskSpawner;
pub use extension_cx::ViewError;
pub use host_functions::ComponentFunc;
pub use host_functions::HostCallContext;
pub use host_functions::HostCallError;
pub use host_functions::HostFunctionDef;
pub use host_functions::HostFunctionFailure;
pub use host_functions::HostFunctionHandler;
pub use host_functions::HostFunctionRefusal;
pub use host_functions::HostFunctionRegistrar;
pub use host_functions::PanicAnswer;
pub use host_functions::Val;
pub use inference::InferenceContribution;
pub use options::Admission;
pub use options::ClientApiOptions;
pub use options::ComposeOptions;
pub use options::ComposeProfile;
pub use options::HostPlatform;
pub use options::InstanceGuard;
pub use options::ListenerOptions;
pub use options::MasterKeyInput;
pub use options::PlatformRule;
pub use options::ProcessPolicy;
pub use options::UnknownPlatform;
pub use options::WasmEngine;
pub use options::Zeroizing;
pub use runtime::ClientApiCheck;
pub use runtime::ClientApiEndpoint;
pub use runtime::ClientApiRebindError;
pub use runtime::ComposedRuntime;
pub use runtime::InstanceGuardKind;
pub use runtime::RuntimeHealthView;
pub use runtime::RuntimePhase;
pub use runtime::ShutdownHandle;
pub use tools::async_trait;
pub use tools::HostTool;
pub use tools::MethodInfo;
pub use tools::ToolDescription;
pub use tools::ToolError;
pub use tools::ToolRefusal;
pub use tools::ToolRegistrar;
